---
title: Paul Pham
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
subtitle: Tech | Product
email: p.pham204@gmail.com
description: I am improving my web development and product experience everyday. I love creating and working with software and products. My passion for learning and technology intersect with software development and product management.

baseurl: ""
url: "https://paulvpham.github.io/"
author:
street_address:
city: Southern California
state:
zip_code:
country:
phone: "(714) 660-7351"
tiles-source: posts
tiles-count: 4
500px_url:
facebook_url:
github_url: https://github.com/PaulVPham
gitlab_url:
googleplus_url:
instagram_url: https://instagram.com/perplepham
linkedin_url: https://www.linkedin.com/in/perple
pinterest_url:
slack_url:
twitter_url: https://twitter.com/paulpham24
markdown: kramdown
sass:
  style: compressed
# Google services
google-analytics: UA-97185002-1
