---
title: Paul Pham
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
subtitle: Tech & Product Driven
email: p.pham204@gmail.com
description: I aspire to discover new challenges, build interesting things, and cook
<<<<<<< HEAD
  new recipes. Everyday is an opportunity to grow. Feel free to click View Projects to the right.
baseurl:
=======
  new recipes. Everyday is an opportunity to grow.
baseurl:
>>>>>>> 31a7317f5b00af8698400ea666bb24646d71c272
url: ''
author:
street_address:
city: Santa Barbara
state: CA
zip_code:
country:
phone: "(714) 660-7351"
tiles-source: posts
tiles-count: 4
500px_url:
facebook_url:
github_url: https://github.com/PaulVPham
gitlab_url:
googleplus_url:
instagram_url: https://instagram.com/perplepham
linkedin_url: https://www.linkedin.com/in/perple
pinterest_url:
slack_url:
twitter_url: https://twitter.com/paulpham24
markdown: kramdown
sass:
  style: compressed
